services:
  - type: web
    name: phomas-diagnostics
    env: node
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm run start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_TELEMETRY_DISABLED
        value: 1
    domains:
      - phomasdiagnostics.onrender.com
